export default {
  filter: import("./filter"),
  notification: import("./notification"),
  event: import("./event"),
  action: import("./action"),
  block: import("./block"),
  blockControl: import("./blockControl"),
  debug: import("./debug"),
  dom: import("./dom"),
  settings: import("./settings"),
  post: import("./post"),
  request: import("./request"),
  template: import("./template"),
  script: import("./script"),
  style: import("./style"),
  error: import("./error"),
};
